# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diff_rcpp <- function(xs) {
    .Call('_amt_diff_rcpp', PACKAGE = 'amt', xs)
}

within_rcpp <- function(x, a, b) {
    .Call('_amt_within_rcpp', PACKAGE = 'amt', x, a, b)
}

random_steps_cpp_one_step <- function(n_rand_steps, start_x, start_y, rel_angle, rand_sl, rand_ta) {
    .Call('_amt_random_steps_cpp_one_step', PACKAGE = 'amt', n_rand_steps, start_x, start_y, rel_angle, rand_sl, rand_ta)
}

rolling_mean <- function(x, win) {
    .Call('_amt_rolling_mean', PACKAGE = 'amt', x, win)
}

rolling_median <- function(x, win) {
    .Call('_amt_rolling_median', PACKAGE = 'amt', x, win)
}

simulate_udf <- function(n_steps, start, nc, nr, mk, hk) {
    .Call('_amt_simulate_udf', PACKAGE = 'amt', n_steps, start, nc, nr, mk, hk)
}

cpp_simulate_ssf <- function(n_steps, start, nc, nr, mk, hk) {
    .Call('_amt_cpp_simulate_ssf', PACKAGE = 'amt', n_steps, start, nc, nr, mk, hk)
}

dispersal_kernel_cpp <- function(cur_x, cur_y, nc, nr, dk, coefs, standardize, first_order_terms, second_order_terms, hab, other_covars, other_covars_indicator, stop) {
    .Call('_amt_dispersal_kernel_cpp', PACKAGE = 'amt', cur_x, cur_y, nc, nr, dk, coefs, standardize, first_order_terms, second_order_terms, hab, other_covars, other_covars_indicator, stop)
}

atan2_north_cpp <- function(y, x) {
    .Call('_amt_atan2_north_cpp', PACKAGE = 'amt', y, x)
}

get_angle_cpp <- function(xy, dir = 0) {
    .Call('_amt_get_angle_cpp', PACKAGE = 'amt', xy, dir)
}

get_angle_cpp1 <- function(xy, dir = 0) {
    .Call('_amt_get_angle_cpp1', PACKAGE = 'amt', xy, dir)
}

get_angle_cpp2 <- function(xy, dir = 0) {
    .Call('_amt_get_angle_cpp2', PACKAGE = 'amt', xy, dir)
}

track_align_cpp <- function(t1, nt, time_tol, type) {
    .Call('_amt_track_align_cpp', PACKAGE = 'amt', t1, nt, time_tol, type)
}

mk_reg <- function(t1, time_dist, time_tol, start) {
    .Call('_amt_mk_reg', PACKAGE = 'amt', t1, time_dist, time_tol, start)
}

mk_reg_old <- function(relocs_time, time_dist, time_tol, start) {
    .Call('_amt_mk_reg_old', PACKAGE = 'amt', relocs_time, time_dist, time_tol, start)
}

track_immobility <- function(t, x, y, period, tol) {
    .Call('_amt_track_immobility', PACKAGE = 'amt', t, x, y, period, tol)
}

